approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules
cacheFolder: .yarn/cache

packageExtensions:
  vue-router@*:
    dependencies:
      "@vue/compiler-sfc": "*"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
