<template>
  <v-container class="login-page pa-4" fluid><v-row class="fill-height align-center justify-center"><v-col cols="12" sm="9" md="8" lg="9" xl="8"><v-card class="login-card overflow-hidden" elevation="0" rounded="xl"><v-row no-gutters><v-col cols="12" md="6" class="login-aside pa-8 pa-md-12"><div class="brand-mark mb-8"><v-icon icon="mdi-shield-check" size="32" /></div><p class="text-overline font-weight-bold">ACCESO INDUSTRIAL</p><h1 class="text-h3 font-weight-bold mt-3">Seguridad que no detiene la operación.</h1><p class="text-body-1 mt-5 text-blue-lighten-5">Auto-chequeo, validación QR y trazabilidad centralizada para cada ingreso.</p><div class="d-flex ga-3 mt-10"><v-chip prepend-icon="mdi-qrcode-scan" color="white" variant="outlined">QR dinámico</v-chip><v-chip prepend-icon="mdi-camera-outline" color="white" variant="outlined">Selfie segura</v-chip></div></v-col><v-col cols="12" md="6" class="pa-8 pa-md-12"><div class="text-overline text-primary font-weight-bold">ADMINISTRACIÓN</div><h2 class="text-h4 font-weight-bold mt-2">Bienvenido</h2><p class="text-medium-emphasis mt-2 mb-8">Ingresa con tu cuenta para administrar el acceso.</p><v-form @submit.prevent="login"><v-text-field v-model="credentials.username" label="Usuario" prepend-inner-icon="mdi-account-outline" variant="outlined" class="mb-2" autofocus/><v-text-field v-model="credentials.password" label="Contraseña" prepend-inner-icon="mdi-lock-outline" type="password" variant="outlined" @keyup.enter="login"/><v-alert v-if="error" type="error" density="compact" variant="tonal" class="my-4">{{ error }}</v-alert><v-btn color="primary" prepend-icon="mdi-login" size="large" type="submit" block :loading="loading">Iniciar sesión</v-btn></v-form></v-col></v-row></v-card></v-col></v-row></v-container>
</template>

<script lang="ts">
import api from '@/services/api'
import { defineComponent, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
export default defineComponent({ name: 'Login', setup() { const router = useRouter(); const credentials = reactive({ username: '', password: '' }); const error = ref(''); const loading = ref(false); const login = async () => { loading.value = true; error.value = ''; try { const { data } = await api.post('/admin/iniciar-sesion', credentials); localStorage.setItem('access-admin-token', data.token); router.push('/') } catch (requestError: any) { error.value = requestError.response?.data?.error ?? 'No se pudo iniciar sesión.' } finally { loading.value = false } }; return { credentials, error, loading, login } } })
</script>

<style scoped>
.login-page { background: #f6f8fc; min-height: 100vh; }.login-card { box-shadow: 0 24px 70px rgba(15, 23, 42, .12) !important; }.login-aside { background: linear-gradient(145deg, #0f172a, #1d4ed8); color: white; min-height: 560px; }.brand-mark { align-items: center; background: rgba(255,255,255,.15); border: 1px solid rgba(255,255,255,.25); border-radius: 16px; display: flex; height: 56px; justify-content: center; width: 56px; }
</style>
