<template>
  <AppFrame>
    <section class="heading mb-6"><div><p class="eyebrow">CONFIGURACIÓN</p><h1 class="text-h4 font-weight-bold">Máquinas y checklists</h1><p class="text-medium-emphasis">Define exactamente qué debe verificar el técnico en cada recorrido.</p></div><v-btn color="primary" prepend-icon="mdi-plus" @click="openCreate">Nueva máquina</v-btn></section>
    <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }}</v-alert>
    <v-row><v-col cols="12" md="5"><v-card class="panel" elevation="0" rounded="xl"><v-list><v-list-subheader>MÁQUINAS</v-list-subheader><v-list-item v-for="machine in machines" :key="machine.id" :active="machine.id===selected?.id" @click="selectMachine(machine)"><template #prepend><v-avatar color="primary" variant="tonal"><v-icon icon="mdi-cog-outline"/></v-avatar></template><v-list-item-title>{{ machine.nombre }}</v-list-item-title><v-list-item-subtitle>{{ machine.codigo }} · {{ machine.ubicacion }}</v-list-item-subtitle><template #append><v-chip size="x-small" :color="machine.estado === 'FUERA_SERVICIO' ? 'error' : 'success'">{{machine.estado}}</v-chip></template></v-list-item></v-list></v-card></v-col><v-col cols="12" md="7"><v-card class="panel" elevation="0" rounded="xl"><v-card-item :title="selected ? `Checklist · ${selected.nombre}` : 'Selecciona una máquina'" subtitle="Los técnicos verán estos puntos en su aplicación."/><v-divider/><v-card-text v-if="selected"><v-list><v-list-item v-for="(item,index) in checklist" :key="item.id"><template #prepend><v-avatar size="28" color="primary" variant="tonal">{{index+1}}</v-avatar></template><v-text-field v-model="item.descripcion" density="compact" hide-details @blur="updateItem(item)"/><template #append><v-btn icon="mdi-delete-outline" color="error" variant="text" @click="deleteItem(item.id)"/></template></v-list-item></v-list><div class="d-flex ga-2 mt-4"><v-text-field v-model="newItem" label="Nuevo punto de verificación" density="comfortable" hide-details @keyup.enter="addItem"/><v-btn color="primary" :disabled="!newItem.trim()" @click="addItem">Agregar</v-btn></div></v-card-text><v-card-text v-else class="text-center text-medium-emphasis py-12">Elige una máquina para configurar su checklist.</v-card-text></v-card></v-col></v-row>
    <v-dialog v-model="machineDialog" max-width="620"><v-card rounded="xl" :title="form.id?'Editar máquina':'Nueva máquina'"><v-card-text><v-row><v-col cols="12" sm="6"><v-text-field v-model="form.codigo" label="Código"/></v-col><v-col cols="12" sm="6"><v-text-field v-model="form.nombre" label="Nombre"/></v-col><v-col cols="12"><v-text-field v-model="form.ubicacion" label="Ubicación"/></v-col><v-col cols="12" sm="6"><v-select v-model="form.estado" :items="states" label="Estado"/></v-col><v-col cols="12" sm="6"><v-select v-model="form.frecuencia_mantenimiento" :items="frequencies" label="Frecuencia"/></v-col></v-row></v-card-text><v-card-actions><v-spacer/><v-btn @click="machineDialog=false">Cancelar</v-btn><v-btn color="primary" @click="saveMachine">Guardar</v-btn></v-card-actions></v-card></v-dialog>
  </AppFrame>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import AppFrame from '@/components/AppFrame.vue'
import api from '@/services/api'
type Machine={id:string,codigo:string,nombre:string,ubicacion:string,estado:string,frecuencia_mantenimiento:string};type Item={id:string,descripcion:string,orden:number}
const machines=ref<Machine[]>([]),selected=ref<Machine|null>(null),checklist=ref<Item[]>([]),newItem=ref(''),error=ref(''),machineDialog=ref(false);const states=['OPERATIVA','MANTENIMIENTO','FUERA_SERVICIO'],frequencies=['diario','semanal','mensual'];const form=reactive<Machine>({id:'',codigo:'',nombre:'',ubicacion:'',estado:'OPERATIVA',frecuencia_mantenimiento:'mensual'})
async function load(){try{machines.value=(await api.get('/admin/maquinas')).data}catch{error.value='No se pudieron cargar las máquinas.'}}
async function selectMachine(machine:Machine){selected.value=machine;checklist.value=(await api.get(`/admin/maquinas/${machine.id}/checklist`)).data}
async function addItem(){if(!selected.value)return;await api.post(`/admin/maquinas/${selected.value.id}/checklist`,{descripcion:newItem.value,orden:checklist.value.length+1});newItem.value='';await selectMachine(selected.value)}
async function updateItem(item:Item){if(!selected.value||!item.descripcion.trim())return;await api.put(`/admin/maquinas/${selected.value.id}/checklist/${item.id}`,item)}
async function deleteItem(id:string){if(!selected.value)return;await api.delete(`/admin/maquinas/${selected.value.id}/checklist/${id}`);checklist.value=checklist.value.filter(x=>x.id!==id)}
function openCreate(){Object.assign(form,{id:'',codigo:'',nombre:'',ubicacion:'',estado:'OPERATIVA',frecuencia_mantenimiento:'mensual'});machineDialog.value=true}
async function saveMachine(){try{const {data}=await api.post('/admin/maquinas',form);machineDialog.value=false;await load();await selectMachine(data)}catch(e:any){error.value=e.response?.data?.error??'No se pudo guardar la máquina'}}onMounted(load)
</script><style scoped>.heading{align-items:center;display:flex;justify-content:space-between;gap:16px}.eyebrow{color:#1976d2;font-size:.75rem;font-weight:800;letter-spacing:.14em}.panel{border:1px solid #e5e7eb}@media(max-width:600px){.heading{align-items:flex-start;flex-direction:column}}</style>
